# Generated by Django 5.2.6 on 2025-09-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_userprofile_portfolio_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configapp.portfolio'),
        ),
    ]
